import { ConfigProvider } from 'antd'
import { typeProps } from './display/itemMap'
import { Auth } from './store/auth'
import { UI } from './store/ui'
import { lang } from './lang'

export const DfAuth = Auth
export const DfUI = UI
export const dfLang = lang
export const AntdConfigProvider = ConfigProvider

export const displayTypeProps = typeProps
export { default as Content } from './display/content'
export { default as Currency } from './display/currency'
export { default as Datetime } from './display/datetime'
export { default as IdCardEncrypt } from './display/idCardEncrypt'
export { default as KeyToValue } from './display/keyToValue'
export { default as Link } from './display/link'
export { default as PhoneEncrypt } from './display/phoneEncrypt'
export { default as Svg } from './display/svg'
export { default as Loading } from './display/loading'
export { default as Lang } from './display/lang'
export { default as DisplayMap } from './display/itemMap'
export { default as Captcha } from './form/item/captcha'
export { default as Cascader } from './form/item/cascader'
export { default as Checkbox } from './form/item/checkbox'
export { default as ImgCaptcha } from './form/item/imgCaptcha'
export { default as Input } from './form/item/input'
export { default as Radio } from './form/item/radio'
export { default as RangeDate } from './form/item/rangeDate'
export { default as Select } from './form/item/select'
export { default as SelectRemote } from './form/item/selectRemote'
export { default as SelectTree } from './form/item/selectTree'
export { default as TextArea } from './form/item/textArea'
export { default as Tree } from './form/item/tree'
export { default as EditForm } from './form/editForm'
export { default as StoreEditForm } from './form/storeEditForm'
export { default as ItemMap } from './form/itemMap'
export { default as ItemMapPlus } from './form/itemMapPlus'
export { default as Validator } from './form/validator'
export { default as formTypeProps } from './form/typeProps'
export { default as ActionsBtn } from './page/_unit/actionsBtn'
export { default as Breadcrumb } from './page/_unit/breadcrumb'
export { default as JumpToOne } from './page/_unit/jumpToOne'
export { default as PageTips } from './page/_unit/pageTips'
export { default as SetSite } from './page/_unit/setSite'
export { default as Add } from './page/add'
export { default as Detail } from './page/detail'
export { default as Edit } from './page/edit'
export { default as List } from './page/list'
export { default as P404 } from './page/p404'
export { default as AutoPage } from './page/autoPage'
export { default as Curd } from './store/curd'
export { default as Form } from './store/form'
export { default as Store } from './store/store'
export { default as AuthContext } from './store/auth'
export { default as UIContext } from './store/ui'
export { default as LangContext } from './lang'
export { default as Footer } from './layout/unit/footer'
export { default as Header } from './layout/unit/header'
export { default as Sider } from './layout/unit/sider'
export { default as Full } from './layout/full'
export { default as LeftSider } from './layout/leftSider'
export { default as Config } from './config'
export { ConfigContext } from './config'
export { default as HTTP } from './unit/http'
// export { default as IStore } from './store/_i'
export { default as StoreRoute } from './route/storeRoute'
export { default as RenderRoute } from './route/renderRoute'
export { default as RemoteComponent } from './unit/remoteComponent'
